"""remove_max_loss_amount_field

Revision ID: 1cd60e94e960
Revises: d0a9a7134cc9
Create Date: 2025-12-21 22:51:28.181988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cd60e94e960'
down_revision: Union[str, Sequence[str], None] = 'd0a9a7134cc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'max_loss_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('max_loss_amount', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
