"""add_enhanced_entry_rationale_fields

Revision ID: d0a9a7134cc9
Revises: 9f434b5cacce
Create Date: 2025-12-21 22:20:37.079922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0a9a7134cc9'
down_revision: Union[str, Sequence[str], None] = '9f434b5cacce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('entry_trigger', sa.Text(), nullable=True))
    op.add_column('trades', sa.Column('target_price', sa.Numeric(precision=20, scale=4), nullable=True))
    op.add_column('trades', sa.Column('stop_loss', sa.Numeric(precision=20, scale=4), nullable=True))
    op.add_column('trades', sa.Column('holding_period', sa.String(length=50), nullable=True))
    op.add_column('trades', sa.Column('position_sizing_rationale', sa.Text(), nullable=True))
    op.add_column('trades', sa.Column('max_loss_amount', sa.Numeric(precision=20, scale=4), nullable=True))
    op.add_column('trades', sa.Column('competitor_analysis', sa.Text(), nullable=True))
    op.add_column('trades', sa.Column('catalyst', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'catalyst')
    op.drop_column('trades', 'competitor_analysis')
    op.drop_column('trades', 'max_loss_amount')
    op.drop_column('trades', 'position_sizing_rationale')
    op.drop_column('trades', 'holding_period')
    op.drop_column('trades', 'stop_loss')
    op.drop_column('trades', 'target_price')
    op.drop_column('trades', 'entry_trigger')
    # ### end Alembic commands ###
